[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
smart_contract = "2fNDYYpjb7EQRdRfR3FwL1M5sJ95LbBY8TMJDiBrUWXx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/xuananle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
